# Generated by Django 4.2.5 on 2023-10-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=1000)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
